# Generated by Django 5.0.6 on 2024-06-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='travel',
        ),
        migrations.AlterField(
            model_name='travel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='travel.hotel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klass', to='travel.klass'),
        ),
    ]
